# Generated by Django 5.1.4 on 2026-05-14 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_company_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('trust_estate', 'Trust / Estate'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], default='individual', max_length=30)),
                ('external_client_id', models.CharField(blank=True, help_text='Optional ID from CCH, SafeSend, or imported client spreadsheet.', max_length=100)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fiscal_year_end_month', models.IntegerField(blank=True, help_text='Example: 12 for calendar year-end, 6 for June year-end.', null=True)),
                ('fiscal_year_end_day', models.IntegerField(blank=True, help_text='Example: 31 for calendar year-end.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederalReturnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business Income'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('s_corporation', 'S Corporation'), ('trust_estate', 'Trust / Estate'), ('exempt_org', 'Exempt Organization / Nonprofit'), ('estate_gift', 'Estate / Gift / GST'), ('employment', 'Employment / Payroll'), ('information', 'Information Return'), ('excise', 'Excise Tax'), ('international', 'International / Foreign Reporting'), ('retirement', 'Retirement / Benefit Plan'), ('estimated_tax', 'Estimated Tax'), ('withholding', 'Withholding'), ('other', 'Other Federal Filing')], max_length=40)),
                ('frequency', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('semiweekly', 'Semiweekly'), ('periodic', 'Periodic'), ('event_based', 'Event Based'), ('fiscal_year_based', 'Fiscal Year Based'), ('one_time', 'One Time')], max_length=40)),
                ('produced_when', models.CharField(blank=True, help_text='Example: Annually after year-end, quarterly after quarter-end, monthly after month-end, event-triggered, etc.', max_length=255)),
                ('default_estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('default_complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20)),
                ('requires_review', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='IRS', max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederalDueDateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('fixed_date', 'Fixed Calendar Date'), ('nth_month_after_year_end', 'Nth Month After Year-End'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('event_based', 'Event Based'), ('recipient_and_irs', 'Separate Recipient and IRS Deadlines'), ('deposit_schedule', 'Deposit Schedule'), ('varies', 'Varies / See Instructions')], max_length=40)),
                ('due_month', models.IntegerField(blank=True, null=True)),
                ('due_day', models.IntegerField(blank=True, null=True)),
                ('extension_month', models.IntegerField(blank=True, null=True)),
                ('extension_day', models.IntegerField(blank=True, null=True)),
                ('months_after_period_end', models.IntegerField(blank=True, null=True)),
                ('due_day_after_period_end', models.IntegerField(blank=True, null=True)),
                ('applies_to_period', models.CharField(blank=True, help_text='Example: Q1, Q2, Q3, Q4, annual, monthly, recipient copy, IRS paper filing, IRS e-file filing.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weekend_holiday_adjustment', models.BooleanField(default=True, help_text='Move to next business day when deadline falls on weekend/federal holiday.')),
                ('active', models.BooleanField(default=True)),
                ('return_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_date_rules', to='core.federalreturntype')),
            ],
        ),
        migrations.CreateModel(
            name='TaxReturnProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('period_start_date', models.DateField(blank=True, help_text='Useful for quarterly, monthly, fiscal-year, or event-based filings.', null=True)),
                ('period_end_date', models.DateField(blank=True, help_text='Usually 12/31 for calendar-year annual returns.', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Calculated from the federal due date rule, but can be overridden.', null=True)),
                ('extended_due_date', models.DateField(blank=True, null=True)),
                ('extension_filed', models.BooleanField(default=False)),
                ('document_status', models.CharField(choices=[('no_docs', 'No documents received'), ('partial_docs', 'Partial documents received'), ('minor_info_missing', 'Waiting on minor information'), ('all_docs_received', 'All documents received')], default='no_docs', max_length=30)),
                ('docs_received_date', models.DateField(blank=True, help_text='Used for FIFO scheduling once documents are complete.', null=True)),
                ('work_status', models.CharField(choices=[('not_started', 'Not Started'), ('ready_to_start', 'Ready to Start'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting_on_client', 'Waiting on Client'), ('under_review', 'Under Review'), ('complete', 'Complete'), ('blocked', 'Blocked')], default='not_started', max_length=30)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20)),
                ('manager_priority_override', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('priority_score', models.IntegerField(default=0)),
                ('scheduled_start_date', models.DateField(blank=True, null=True)),
                ('scheduled_end_date', models.DateField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_preparer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_preparation_projects', to=settings.AUTH_USER_MODEL)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_projects', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_projects', to='core.client')),
                ('due_date_rule', models.ForeignKey(blank=True, help_text='Specific deadline rule used for this client project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to='core.federalduedaterule')),
                ('return_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_projects', to='core.federalreturntype')),
            ],
            options={
                'ordering': ['due_date', '-priority_score', 'client__name'],
            },
        ),
    ]
